# Generated by Django 5.2.5 on 2025-08-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auth_provider'),
    ]

    operations = [
    ]
