# Generated by Django 5.2.5 on 2025-08-19 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hourly Rate'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Job Title'),
        ),
    ]
