# Generated by Django 5.2.5 on 2025-08-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_workerprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='location',
        ),
    ]
