# Generated by Django 5.2.5 on 2025-08-23 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_clientprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Egyptian phone number (11 digits starting with 01)', regex='^01[0-9]{9}$')], verbose_name='Phone Number'),
        ),
    ]
