# Generated by Django 5.2.5 on 2025-08-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_location_to_workerprofile'),
        ('accounts', '0005_alter_user_phone'),
    ]

    operations = [
    ]
