# Generated by Django 5.2.5 on 2025-09-05 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20250824_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated price for one service', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimated Service Price'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='services_provided',
            field=models.TextField(blank=True, help_text='List of services the worker provides', verbose_name='Services Provided'),
        ),
    ]
