# Generated by Django 5.2.5 on 2025-09-05 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_workerprofile_estimated_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated price for services', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimated Price'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='services_provided',
            field=models.TextField(blank=True, help_text='List of services this worker can provide', verbose_name='Services Provided'),
        ),
    ]
