# Generated by Django 5.2.5 on 2025-09-06 11:23

from django.db import migrations, models, connection


def check_and_fix_certifications_field(apps, schema_editor):
    """
    Check if certifications field exists and fix its constraints
    """
    db_alias = schema_editor.connection.alias
    
    with connection.cursor() as cursor:
        # Check if the field exists and its properties
        cursor.execute("""
            SELECT column_name, is_nullable, column_default 
            FROM information_schema.columns 
            WHERE table_name = 'accounts_workerprofile' 
            AND column_name = 'certifications'
        """)
        
        result = cursor.fetchone()
        
        if result:
            column_name, is_nullable, column_default = result
            
            if is_nullable == 'NO':
                # Field exists but is NOT NULL, let's make it nullable and set default
                print("Fixing existing certifications field...")
                
                # First, update any NULL values to empty string
                cursor.execute("""
                    UPDATE accounts_workerprofile 
                    SET certifications = '' 
                    WHERE certifications IS NULL
                """)
                
                # Then alter the column to allow NULL and set default
                cursor.execute("""
                    ALTER TABLE accounts_workerprofile 
                    ALTER COLUMN certifications DROP NOT NULL
                """)
                
                cursor.execute("""
                    ALTER TABLE accounts_workerprofile 
                    ALTER COLUMN certifications SET DEFAULT ''
                """)
                
                print("Certifications field fixed successfully!")
        else:
            # Field doesn't exist, create it
            print("Creating certifications field...")
            cursor.execute("""
                ALTER TABLE accounts_workerprofile 
                ADD COLUMN certifications TEXT DEFAULT '' NOT NULL
            """)


def reverse_certifications_field(apps, schema_editor):
    """
    Reverse the certifications field fix
    """
    # This is a no-op since we're just fixing an existing field
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_workerprofile_estimated_price_and_more'),
    ]

    operations = [
        migrations.RunPython(
            check_and_fix_certifications_field,
            reverse_certifications_field,
        ),
    ]


