# Generated by Django 5.2.5 on 2025-09-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_workerprofile_estimated_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography', null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Worker certifications and qualifications', verbose_name='Certifications'),
        ),
    ]
