# Generated by Django 5.2.5 on 2025-09-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_workerprofile_estimated_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='neighborhood',
            field=models.CharField(blank=True, help_text="Worker's neighborhood or area", max_length=100, null=True, verbose_name='Neighborhood'),
        ),
    ]
