# Generated by Django 5.2.5 on 2025-09-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_bio'),
        ('accounts', '0010_workerprofile_certifications_and_more'),
    ]

    operations = [
    ]
