# Generated by Django 5.2.5 on 2025-09-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_workerprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='certifications',
            field=models.TextField(blank=True, default='', help_text='Professional certifications and qualifications', verbose_name='Certifications'),
        ),
    ]
