# Generated by Django 5.2.5 on 2025-09-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20250909_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography', null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='certifications',
            field=models.TextField(blank=True, default='', help_text='Professional certifications and qualifications', verbose_name='Certifications'),
        ),
    ]
