# Generated by Django 5.2.5 on 2025-09-09 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_bio_alter_workerprofile_certifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('id_card_front', models.ImageField(upload_to='verifications/id_cards/front/')),
                ('id_card_back', models.ImageField(upload_to='verifications/id_cards/back/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='accounts.workerprofile')),
            ],
        ),
    ]
