# Generated by Django 5.2.5 on 2025-09-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_taken',
            field=models.BooleanField(default=False, verbose_name='تم اتخاذ إجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت اتخاذ الإجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='نوع الإجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='job_description',
            field=models.TextField(blank=True, verbose_name='وصف العمل المطلوب'),
        ),
        migrations.AddField(
            model_name='notification',
            name='location_address',
            field=models.TextField(blank=True, verbose_name='عنوان الموقع'),
        ),
        migrations.AddField(
            model_name='notification',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='notification',
            name='location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='notification',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر المعروض من العميل'),
        ),
        migrations.AddField(
            model_name='notification',
            name='requires_action',
            field=models.BooleanField(default=False, verbose_name='يتطلب إجراءً'),
        ),
        migrations.AddField(
            model_name='notification',
            name='service_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الخدمة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الخدمة'),
        ),
    ]
