# Generated by Django 5.2.5 on 2025-09-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='location_address',
            field=models.TextField(blank=True, default='عنوان غير محدد', verbose_name='عنوان الموقع'),
        ),
    ]
