# Generated by Django 5.2.5 on 2025-08-22 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0003_alter_service_options_alter_servicecategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negotiation',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.service'),
        ),
        migrations.AddIndex(
            model_name='negotiation',
            index=models.Index(fields=['order', 'date_created'], name='orders_nego_order_i_2cb66a_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['order', 'provider'], name='orders_offe_order_i_cf7df4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status', 'is_deleted'], name='orders_orde_custome_e7c504_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['service'], name='orders_orde_service_6af3e9_idx'),
        ),
    ]
