# Generated by Django 5.2.5 on 2025-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, help_text='Expected delivery/completion time', null=True),
        ),
    ]
