# Generated by Django 5.2.5 on 2025-08-22 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, default='Notspecified', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='Not specified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(default='Not specified', on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='Not specified', max_length=200),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'service'], name='services_fa_user_id_3f41c0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_deleted', 'is_active'], name='services_se_is_dele_4302c5_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='services_se_categor_7ca2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['provider'], name='services_se_provide_b7a0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['city'], name='services_se_city_665d50_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='services_se_created_ebde2c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['name'], name='services_se_name_dc5d11_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_deleted'], name='services_se_is_dele_584955_idx'),
        ),
    ]
