# Generated by Django 5.2.5 on 2025-09-09 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_platformsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='admin',
            field=models.ForeignKey(default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('review', 'Review'), ('system', 'System'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('bulk_update_settings', 'Bulk Update Settings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='target_model',
            field=models.CharField(max_length=100),
        ),
    ]
