# Generated by Django 5.2.5 on 2025-08-22 14:15

import django.db.models.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_negotiation_options_alter_offer_options_and_more'),
        ('reviews', '0002_rename_rating_review_score_and_more'),
        ('services', '0003_alter_service_options_alter_servicecategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['service', 'is_deleted'], name='reviews_rev_service_4d8b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer'], name='reviews_rev_custome_931f64_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('service', 'customer', 'order'), name='unique_review_per_order'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='score_between_1_5'),
        ),
    ]
