# Generated by Django 5.2.5 on 2025-08-23 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service'], name='ratings_rat_service_8b9e1f_idx'), models.Index(fields=['customer'], name='ratings_rat_custome_ef86a3_idx')],
                'unique_together': {('service', 'customer')},
            },
        ),
    ]
