# Generated by Django 5.2.5 on 2025-09-08 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('paid', 'تم الدفع'), ('unpaid', 'لم يتم الدفع'), ('pending', 'قيد الانتظار'), ('overdue', 'متأخر')], default='unpaid', max_length=10, verbose_name='حالة الفاتورة')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقداً'), ('card', 'بطاقة ائتمان'), ('wallet', 'محفظة إلكترونية'), ('bank', 'تحويل بنكي')], max_length=10, null=True, verbose_name='طريقة الدفع')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-issued_at'],
            },
        ),
    ]
