<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-23 22:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

=======
# Generated by Django manually
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> cdf5adee20680c4021187124d2966897cb0e740f

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('paid', 'تم الدفع'), ('unpaid', 'لم يتم الدفع')], default='unpaid', max_length=10, verbose_name='حالة الفاتورة')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-issued_at'],
            },
=======
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.booking')),
            ],
>>>>>>> cdf5adee20680c4021187124d2966897cb0e740f
        ),
    ]
