# Generated by Django 5.2.5 on 2025-09-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'نقداً'), ('card', 'بطاقة ائتمان'), ('wallet', 'محفظة إلكترونية'), ('bank', 'تحويل بنكي')], max_length=10, null=True, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'تم الدفع'), ('unpaid', 'لم يتم الدفع'), ('pending', 'قيد الانتظار'), ('overdue', 'متأخر')], default='unpaid', max_length=10, verbose_name='حالة الفاتورة'),
        ),
    ]
