# Generated by Django 5.2.5 on 2025-09-08 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_due_date_invoice_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='رسوم المنصة (5%)')),
                ('net_earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='صافي الأرباح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_earnings', to='invoices.invoice', verbose_name='الفاتورة')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL, verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'أرباح العامل',
                'verbose_name_plural': 'أرباح العمال',
                'ordering': ['-created_at'],
            },
        ),
    ]
