# Generated by Django 5.2.5 on 2025-09-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
        ('invoices', '0002_invoice_booking'),
        ('invoices', '0003_workerearnings'),
    ]

    operations = [
    ]
