# Generated by Django 5.2.5 on 2025-09-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_merge_20250909_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='booking',
        ),
    ]
