# Generated by Django 5.2.5 on 2025-08-26 23:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False, verbose_name='يستطيع التعديل')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مشاركة موقع',
                'verbose_name_plural': 'مشاركات المواقع',
            },
        ),
        migrations.AlterModelOptions(
            name='userlocation',
            options={'ordering': ['-created_at'], 'verbose_name': 'موقع المستخدم', 'verbose_name_plural': 'مواقع المستخدمين'},
        ),
        migrations.AddField(
            model_name='userlocation',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='هل هذا الموقع الرئيسي للمستخدم؟', verbose_name='موقع رئيسي'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='location_type',
            field=models.CharField(choices=[('home', 'المنزل'), ('work', 'العمل'), ('favorite', 'المفضلة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع الموقع'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='name',
            field=models.CharField(blank=True, help_text="اسم تعريفي للموقع مثل 'المنزل' أو 'العمل'", max_length=100, null=True, verbose_name='اسم الموقع'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='الإحداثيات الجغرافية للموقع', null=True, srid=4326, verbose_name='الموقع الجغرافي'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'created_at'], name='location_us_user_id_d112cd_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'location_type'], name='location_us_user_id_1561a2_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['created_at'], name='location_us_created_7647f7_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['is_primary'], name='location_us_is_prim_a13c86_idx'),
        ),
        migrations.AddField(
            model_name='locationshare',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.userlocation', verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='locationshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_locations', to=settings.AUTH_USER_MODEL, verbose_name='المشارك من'),
        ),
        migrations.AddField(
            model_name='locationshare',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_locations', to=settings.AUTH_USER_MODEL, verbose_name='المشارك مع'),
        ),
        migrations.AlterUniqueTogether(
            name='locationshare',
            unique_together={('shared_by', 'shared_with', 'location')},
        ),
    ]
