# Generated by Django 5.2.5 on 2025-09-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_userlocation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='additional_details',
            field=models.TextField(blank=True, help_text='أي تفاصيل إضافية تساعد في الوصول للموقع', null=True, verbose_name='تفاصيل إضافية'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الشقة'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='building_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم العمارة'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='floor_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الطابق'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='landmark',
            field=models.CharField(blank=True, help_text='مثل: بجوار مدرسة، أمام مسجد، قرب محطة', max_length=200, null=True, verbose_name='معلم مميز'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي'),
        ),
    ]
